version: "3.9"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - .:/app
            - ./php.ini:/usr/local/etc/php-fpm.d/99-overrides.ini
            - ./php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    nginx:
        image: nginx:alpine
        working_dir: /app
        volumes:
            - .:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9000:80"
        links:
            - php
